import Head from "next/head";
import Image from "next/image";
import { Button } from "../components";
import { Moon_Dance } from "@next/font/google";

const moon = Moon_Dance({ subsets: ["latin"], weight: "400" });
export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="h-screen grid grid-rows-2 gap-y-12 w-full bg-[#001118]">
        <div className="w-full h-full grid grid-cols-3">
          <div className="relative flex flex-col-reverse  col-start-2">
            <h1 className={`text-4xl z-40 text-center ${moon.className} bg-[#001118] w-full text-white relative z-10 `}>will you date me?</h1>
            <Image width={483} height={585} className="object-cover z-0 absolute top-0  h-full w-full object-top" src={"/catdate.webp"} />
          </div>
        </div>
        <div className="relative flex justify-center gap-x-12">
          <Button />
          <button className="absolute flex justify-center group items-center top-8 left-[55%]">
            <span className="relative left-4  group-hover:-translate-x-8 transition-transform duration-300 ease-out">yes</span>
            <span className="opacity-0 translate-x-8 transition-all duration-300 grid place-items-center group-hover:translate-x-0 group-hover:opacity-100">
              <img className="w-8" src="/cat.png" alt="" />
            </span>
          </button>
        </div>
      </main>
    </>
  );
}
